server.port: 8099

spring:
  application:
    name: registryservice
  cloud:
    config:
      uri: http://localhost:8091
      username: root
      password: s3cr3t
    compatibility-verifier:
      enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

security:
  basic:
    enabled: false