#Application Configuration
server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always

# To See H2 Console in Browser:
# http://localhost:8092/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url: jdbc:mysql://localhost:3306/userservice?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
      basic:
        enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8097/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"


springdoc:
  api-docs:
    path: /ts-api-docs
  swagger-ui:
    path: /index.html

env:
  jwtSecret: fdsfdfokpokposdwkfposksd
  jwtExpiration: 200000
  refreshTokenExpiration: 30000
