#Application Configuration
server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always

spring:
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url: jdbc:mysql://localhost:3306/userservice?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    basic:
      enabled: false
  cloud:
    config:
      uri: http://localhost:8097
      username: root
      password: s3cr3t
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
