server:
    port: 8095

spring:
    application:
        name: configservice
    datasource:
        url: jdbc:mysql://localhost:3306/configservice?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: root
        password:
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    h2:
        console:
            enabled: true
            path: /console
    cloud:
        config:
            uri: http://localhost:8081
            username: root
            password: s3cr3t
    boot:
        admin:
            client:
                url: http://localhost:8086

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8099/eureka

management:
    endpoints:
        web:
            exposure:
                include: "*"




#server.port=${PORT:8082}
#spring.cloud.config.server.git.uri=https://github.com/tropsmart/TS_mi_config.git

#spring.security.user.name: root
#spring.security.user.password: s3cr3t
#spring.cloud.config.server.native.searchLocations=file://${user.home}/MicroService/centralProperties/

#SPRING_PROFILES_ACTIVE=native
#spring.config.import=optional:configserver:http://localhost:8888/
