server:
  port: 8080

spring:
  application:
    name: gatewayservice
  cloud:
    config:
      uri: http://localhost:8081
      username: root
      password: s3cr3t
    compatibility-verifier:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

